Github actions
FriendsOfSymfony/FOSCKEditorBundle pull request #223
Opened 2020-12-13 15:23 UTC by VincentLanglet

2020-12-13 15:32 UTC, VincentLanglet commented
I started working on https://github.com/FriendsOfSymfony/FOSCKEditorBundle/issues/222 @jmsche but the github actions is not triggered. Maybe you know why ?

Is there something to configure on the repository for github actions to work ? @lsmith77

2020-12-13 15:37 UTC, jmsche commented
As it is not merged in this repository, actions are run in your own repo only, see https://github.com/VincentLanglet/FOSCKEditorBundle/actions

2020-12-13 15:44 UTC, VincentLanglet commented
> As it is not merged in this repository, actions are run in your own repo only, see https://github.com/VincentLanglet/FOSCKEditorBundle/actions

Thanks

2020-12-13 15:44 UTC, jmsche requested changes

2020-12-13 15:44 UTC, jmsche commented on .github/workflows/test.yaml
> +        runs-on: ubuntu-18.04
Maybe run against ubuntu-20.04 instead?

2020-12-13 20:04 UTC, VincentLanglet commented on .github/workflows/test.yaml
> +        runs-on: ubuntu-18.04
20.0.4 has only php 7.4+ pre-installed.

2020-12-13 20:18 UTC, jmsche commented on .github/workflows/test.yaml
> +        runs-on: ubuntu-18.04
Not a problem as you don't use Ubuntu's PHP installed version, but shivammathur's

2020-12-13 20:22 UTC, jmsche commented
You may want to change the PR's title as it also drop 3.4 & add PHP 8 support :)

2020-12-15 10:13 UTC, jmsche requested changes

2020-12-15 10:13 UTC, jmsche commented on .github/workflows/test.yaml
> +                  tools: composer:v2
```suggestion
                  tools: composer:v2
                  extensions: zip
```

2020-12-15 22:28 UTC, VincentLanglet commented
@kunicmarko20 @lsmith77 This seems ready to be merged to me :)

Tests are green: https://github.com/VincentLanglet/FOSCKEditorBundle/actions/runs/424310014

2020-12-22 15:24 UTC, kunicmarko20 commented
Hey @VincentLanglet, sorry but I am not a maintainer of this package anymore, hopefully, @lsmith77 or @ElectricMaxxx could help with it.

2020-12-22 16:08 UTC, VincentLanglet commented
> Hey @VincentLanglet, sorry but I am not a maintainer of this package anymore, hopefully, @lsmith77 or @ElectricMaxxx could help with it.

No problem, I had just trouble to find the maintainer of this package ; didn't find the information on the Readme.

2020-12-22 16:13 UTC, lsmith77 commented on .styleci.yml
> -  - short_array_syntax
why did you make changes here?

2020-12-22 16:14 UTC, lsmith77 commented
honestly this package might not have an active maintainer right now.

but as always, I am willing to do the final review if people like you put int the effort.
in that spirit we can also discuss potentially you becoming the official maintainer.

I added a small question but otherwise it looks good indeed!

2020-12-22 16:47 UTC, VincentLanglet commented on .styleci.yml
> -  - short_array_syntax
I don't know but I got this error https://github.styleci.io/analyses/1beGJL?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Maybe the ci changed.

2020-12-22 16:55 UTC, VincentLanglet commented
> honestly this package might not have an active maintainer right now.

It seems indeed.
 
> but as always, I am willing to do the final review if people like you put int the effort.

Thanks 

> in that spirit we can also discuss potentially you becoming the official maintainer.

I don't know much about this package, maybe with a "look for maintainer" issue, there will be better candidate.
I currently trying to add the php 8 compatibility on a multiple bundles. But I'm not against helping more.

2020-12-24 10:10 UTC, merged

2020-12-24 10:10 UTC, lsmith77 commented
thank you!

I guess only after merging it will be possible for you to confirm if the setup works properly.

2020-12-24 10:11 UTC, lsmith77 commented
so are you able to confirm it works now?
also I just noticed that we then also need to update the badges in the README to no longer point to travis-ci
https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/2.x/README.md

2020-12-24 10:39 UTC, lsmith77 commented
see also #224

2020-12-24 13:55 UTC, VincentLanglet commented
> so are you able to confirm it works now?

My project have other dependencies which are not compatible with PHP8, so I currently cannot test it.
I would recommend to create a release and see what happen.
- either it works for php 8
- either it doesn't, but it still works as good as currently ; people will submit issue that we can fix.

> also I just noticed that we then also need to update the badges in the README to no longer point to travis-ci
> https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/2.x/README.md

Fixed in https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/225

2020-12-24 16:00 UTC, jmsche commented
@lsmith77 I just tested against a new sample Symfony app, using Symfony 5.2.1 & PHP 8.0.0 & it works :)